version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: devfashion_apache
    restart: always
    volumes:
      - .:/var/www/html/
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '80:80'
    networks:
      - devfashion
    environment:
      TZ: "America/Maceio"
  mysql:
    container_name: devfashion_mysql
    restart: always
    image: mysql:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: devfashion@!#
      MYSQL_DATABASE: devfashion
      MYSQL_PASSWORD: 02234
      TZ: "America/Maceio"
    ports:
      - '3306:3306'
    networks:
      - devfashion
networks:
  devfashion:
    driver: bridge
