insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Branca Anjo Ak47",49.90,1,"roupas/masculino/masc_01");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Preta Simples",29.90,1,"roupas/masculino/masc_02");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Preta Símbolo Bem & Mal",69.90,1,"roupas/masculino/masc_03");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Social Manga Longa Preta",89.90,1,"roupas/masculino/masc_04");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Moleton Preta",79.90,1,"roupas/masculino/masc_05");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Casaco Boy ESD",119.90,1,"roupas/masculino/masc_06");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa White Rabbit",39.90,1,"roupas/masculino/masc_07");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Urso paris",89.90,1,"roupas/masculino/masc_08");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Básica Preta",49.90,1,"roupas/masculino/masc_09");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Preta Leão",79.90,1,"roupas/masculino/masc_010");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Puma",69.90,1,"roupas/masculino/masc_011");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Laud",89.90,1,"roupas/masculino/masc_012");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa vintage",29.90,1,"roupas/masculino/masc_013");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Calça jeans clara",19.90,1,"roupas/masculino/masc_014");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Calça preta lisa",99.90,1,"roupas/masculino/masc_015");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa Smile",49.90,1,"roupas/masculino/masc_016");

insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Calça Wide Cintura Alta",89.90,2,"roupas/feminino/fem_01");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Cropped Preto Manga Longa",59.90,2,"roupas/feminino/fem_02");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Blusa Duna Branca Lisa",59.90,2,"roupas/feminino/fem_03");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Short Jeans Cintura Alta",59.90,2,"roupas/feminino/fem_04");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Cropped moletom rosa",99.90,2,"roupas/feminino/fem_05");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Cropped moletom cinza",49.90,2,"roupas/feminino/fem_06");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Short jeans",99.90,2,"roupas/feminino/fem_07");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Short básico",89.90,2,"roupas/feminino/fem_08");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Short preto liso",79.90,2,"roupas/feminino/fem_09");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa florada",39.90,2,"roupas/feminino/fem_010");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Vestido preto florado",49.90,2,"roupas/feminino/fem_011");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Vestido longo estampado",89.90,2,"roupas/feminino/fem_012");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Vestido branco simples",59.90,2,"roupas/feminino/fem_013");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa stitch",29.90,2,"roupas/feminino/fem_014");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("T-shirt Feminina Seguro Estou",69.90,2,"roupas/feminino/fem_015");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Cropped moletom",79.90,2,"roupas/feminino/fem_016");

insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto Lider de Uso 2023",59.90,3,"roupas/infantil/inf_01");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto Cigana Safari, 3 Peças",99.90,3,"roupas/infantil/inf_02");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Bermuda Infantil Menino 3 Peças",49.90,3,"roupas/infantil/inf_03");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto Infantil Aballa",39.90,3,"roupas/infantil/inf_04");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto unicórnio",89.90,3,"roupas/infantil/inf_05");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto melhores amigas",29.90,3,"roupas/infantil/inf_06");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto básico",69.90,3,"roupas/infantil/inf_07");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto minnie",39.90,3,"roupas/infantil/inf_08");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto básico simples",89.90,3,"roupas/infantil/inf_09");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto cachorrinho coração",79.90,3,"roupas/infantil/inf_010");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisas básicas estampadas",89.90,3,"roupas/infantil/inf_011");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Macação dino",99.90,3,"roupas/infantil/inf_012");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Vestido florado",69.90,3,"roupas/infantil/inf_013");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Vestido duas cores",89.90,3,"roupas/infantil/inf_014");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Vestido rosa",29.90,3,"roupas/infantil/inf_015");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Conjunto lacoste",59.90,3,"roupas/infantil/inf_016");

insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Calça Pantalona Preta Plus Size",69.90,4,"roupas/plus_size/plus_01");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Vestido de Chiffon",79.90,4,"roupas/plus_size/plus_02");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Blusa Plus Size Verão",59.90,4,"roupas/plus_size/plus_03");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Blusa Plus Size Gola em V",69.90,4,"roupas/plus_size/plus_04");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Calça jeans",79.90,4,"roupas/plus_size/plus_05");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa básica preta",89.90,4,"roupas/plus_size/plus_06");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camis Duff Beer",99.90,4,"roupas/plus_size/plus_07");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa moletom preta",29.90,4,"roupas/plus_size/plus_08");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camias Ohana",59.90,4,"roupas/plus_size/plus_09");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa preta listra",59.90,4,"roupas/plus_size/plus_010");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisa básica preta V2",49.90,4,"roupas/plus_size/plus_011");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Boddy verde",79.90,4,"roupas/plus_size/plus_012");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Short jeans",89.90,4,"roupas/plus_size/plus_013");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Bermuda jeans preta",69.90,4,"roupas/plus_size/plus_014");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Camisaa moletom preta V2",39.90,4,"roupas/plus_size/plus_015");
insert into rpa_roupa (rpa_nome, rpa_preco, rpa_tipo, rpa_caminho_imagem) values ("Vestido básico vermelho",79.90,4,"roupas/plus_size/plus_016");